language: java
jdk:
  - openjdk11

branches:
  only:
    - main

# Travis CI Sever's home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_install:
  - chmod +x gradlew
#CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - xengom@naver.com