language: java
jdk:
  - openjdk11

branches:
  only:
    - main

# Travis CI Sever's home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_install:
  - chmod +x gradlew

before_deploy:
  - zip -r boardJPA
  - mkdir -p deploy
  - mv boardJPA.zip deploy/boardJPA.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY #Travis repo setting 설정값
    secret_access_key: $AWS_SECRET_KEY
    bucket: xengom-springboot-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근 private
    local_dir: deploy
    wait-until-deployed: true

#CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - xengom@naver.com